apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-products
  template:
    metadata:
      labels:
        app: api-products
    spec:
      containers:
      - name: api-products
        image: api-products:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: MONGO_USER
          value: products
        - name: MONGO_PASSWORD
          value: apiProducts
        - name: MONGO_DB
          value: products_db
        - name: MONGO_HOST
          value: mongo-products
        - name: MONGO_PORT
          value: "27017"

        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: api-products
spec:
  type: NodePort
  selector:
    app: api-products
  ports:
  - port: 8001
    targetPort: 8001
