version: '3.9'

services:
  db:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - backend
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"

  api:
    build: .
    command: uvicorn app.main:app --host ${API_HOST} --port ${API_PORT}
    volumes:
      - ./:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - MONGO_HOST=db
      - MONGO_PORT=${MONGO_PORT}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
