# k8s/mongo-products-sts.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-products
spec:
  serviceName: mongo-products
  replicas: 1
  selector:
    matchLabels:
      app: mongo-products
  template:
    metadata:
      labels:
        app: mongo-products
    spec:
      containers:
      - name: mongo
        image: mongo:4.4
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: products
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: apiProducts
        - name: MONGO_INITDB_DATABASE
          value: products_db
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-products
spec:
  clusterIP: None
  selector:
    app: mongo-products
  ports:
  - port: 27017
    targetPort: 27017
